### ISSUE TITLE
Anyone setup to update the METADATA.jl with v0.1.0?

### ISSUE THREAD

**Issue by acrosby** [acrosby/GreatCircle.jl#3]
It might take me a while to get set back up to issue a pull request to the Julialang METADATA.jl for https://github.com/acrosby/GreatCircle.jl/releases/tag/v0.1.0 update (edited to minor version)

@tkelman @evanfields ? No worries if you don't have the time.

**Comment by tkelman** [comment]
Tags should use semantic versioning, so 3 digits. Since the only thing that changed was the Travis CI configuration, there's no need to tag that. You should enable the service though.

**Comment by acrosby** [comment]
Sure, thanks for the config btw.

**Comment by tkelman** [comment]
Oh I see you never published 0.0.2 to METADATA either. Since https://github.com/acrosby/GreatCircle.jl/pull/1 dropped support for Julia 0.3, it would actually need to use a new minor package version. If you make a git tag of latest master as v0.1.0, then @evanfields could make the METADATA pull request (or you could consider granting him collaborator access here so he could also push the git tag?)

**Comment by acrosby** [comment]
I've changed the current master head to v0.1.0, so it is ready. I can do it if no one gets around to it, this issue will just remind me.

**Comment by acrosby** [comment]
nevermind, i just did it manually. thanks.

https://github.com/JuliaLang/METADATA.jl/pull/6794/commits/ab2442230d424ab9c54f2ca726eaa93a45319069

**Comment by tkelman** [comment]
Did you enable Travis CI? Should be as simple as "login with github" and a click to enable at https://travis-ci.org/acrosby/GreatCircle.jl if I remember correctly

**Comment by acrosby** [comment]
Not yet, but that seemed to be the case
